# Generated by Django 5.1.6 on 2025-03-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customeruser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('collaborator_email_1', models.EmailField(blank=True, max_length=254, null=True)),
                ('collaborator_email_2', models.EmailField(blank=True, max_length=254, null=True)),
                ('venue', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('registration_fee', models.TextField(blank=True, null=True)),
                ('sponsor_1_title', models.CharField(blank=True, max_length=255, null=True)),
                ('sponsor_1_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sponsor_1_image', models.ImageField(blank=True, null=True, upload_to='sponsor_images/')),
                ('sponsor_2_title', models.CharField(blank=True, max_length=255, null=True)),
                ('sponsor_2_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sponsor_2_image', models.ImageField(blank=True, null=True, upload_to='sponsor_images/')),
                ('sponsor_3_title', models.CharField(blank=True, max_length=255, null=True)),
                ('sponsor_3_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sponsor_3_image', models.ImageField(blank=True, null=True, upload_to='sponsor_images/')),
            ],
        ),
    ]
